version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=2046655957:AAET4pgQqtaZgNHSMttpo8ZeL39Vdt_Uk7A
      - user_ids=244535415
      - group_ids=-1
      - PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped
